//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotepadV2_by_Jurij15.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class userPreferencs : global::System.Configuration.ApplicationSettingsBase {
        
        private static userPreferencs defaultInstance = ((userPreferencs)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new userPreferencs())));
        
        public static userPreferencs Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string CanUseExtensions {
            get {
                return ((string)(this["CanUseExtensions"]));
            }
            set {
                this["CanUseExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string CanUseLegacyWebBrowser {
            get {
                return ((string)(this["CanUseLegacyWebBrowser"]));
            }
            set {
                this["CanUseLegacyWebBrowser"] = value;
            }
        }
    }
}
