//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotepadV2_by_Jurij15.Windows {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class WebBrowserSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static WebBrowserSettings defaultInstance = ((WebBrowserSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new WebBrowserSettings())));
        
        public static WebBrowserSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.google.com")]
        public string HomePageAdress {
            get {
                return ((string)(this["HomePageAdress"]));
            }
            set {
                this["HomePageAdress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Bookmark1 {
            get {
                return ((string)(this["Bookmark1"]));
            }
            set {
                this["Bookmark1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Bookmark2 {
            get {
                return ((string)(this["Bookmark2"]));
            }
            set {
                this["Bookmark2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Bookmark3 {
            get {
                return ((string)(this["Bookmark3"]));
            }
            set {
                this["Bookmark3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Bookmark4 {
            get {
                return ((string)(this["Bookmark4"]));
            }
            set {
                this["Bookmark4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Bookmark5 {
            get {
                return ((string)(this["Bookmark5"]));
            }
            set {
                this["Bookmark5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("www.google.com")]
        public string DefaultPage {
            get {
                return ((string)(this["DefaultPage"]));
            }
            set {
                this["DefaultPage"] = value;
            }
        }
    }
}
